<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from 'vue'
import { Download, FolderOpen, MousePointer2, Redo2, RotateCcw, SquareDashedMousePointer, Trash2, Upload, ZoomIn, ZoomOut } from 'lucide-vue-next'
import { api } from '../lib/api'
import { notify, refresh, state } from '../stores/app'
import type { Media, Mode, Region, VideoRange } from '../types'

type Tool = 'select' | 'region'
type Transform = { id: string; kind: 'move' | 'resize'; start: { x: number; y: number }; region: Region }
type Pan = { start: { x: number; y: number }; origin: { x: number; y: number } }
const media = ref<Media | null>(null); const dragging = ref(false); const authorized = ref(false); const mode = ref<Mode>('crop'); const quality = ref(90); const outputFormat = ref('png'); const videoRange = ref<VideoRange>({ kind: 'all', start: 0, end: 0 }); const regions = ref<Region[]>([]); const selected = ref<string | null>(null); const history = ref<Region[][]>([]); const redoStack = ref<Region[][]>([]); const input = ref<HTMLInputElement | null>(null); const drawing = ref<{ x: number; y: number } | null>(null); const transform = ref<Transform | null>(null); const panning = ref<Pan | null>(null); const tool = ref<Tool>('select'); const zoom = ref(100); const pan = ref({ x: 0, y: 0 }); const hasFitted = ref(false); const stage = ref<HTMLElement | null>(null); const mediaElement = ref<HTMLImageElement | HTMLVideoElement | null>(null); const selectionLayer = ref<HTMLElement | null>(null); const bounds = ref({ left: 0, top: 0, width: 0, height: 0 })
const modes: [Mode, string, string][] = [['crop', '局部修复', '原尺寸移除选区内容，未选区域与图片尺寸保持不变'], ['blur', '模糊覆盖', '仅模糊所选区域'], ['solid', '纯色覆盖', '仅用纯色覆盖所选区域'], ['smart', 'AI 智能修复', '使用已配置的 AI 图像修复；视频使用局部去标识修复']]
const preview = computed(() => media.value?.previewUrl || ''); const layerStyle = computed(() => ({ left: `${bounds.value.left}px`, top: `${bounds.value.top}px`, width: `${bounds.value.width}px`, height: `${bounds.value.height}px` })); const assetStyle = computed(() => media.value ? { width: `${media.value.width ?? 1}px`, height: `${media.value.height ?? 1}px`, transform: `translate(-50%, -50%) translate(${pan.value.x}px, ${pan.value.y}px) scale(${zoom.value / 100})` } : undefined); const isVideo = computed(() => media.value?.mediaType === 'video'); const duration = computed(() => media.value?.duration ?? 0)
function cloneRegions(value: Region[]) { return value.map(region => ({ ...region })) }
function snapshot() { history.value.push(cloneRegions(regions.value)); if (history.value.length > 20) history.value.shift(); redoStack.value = [] }
function updateBounds() { const frame = stage.value?.getBoundingClientRect(); const asset = mediaElement.value?.getBoundingClientRect(); if (!frame || !asset) return; bounds.value = { left: asset.left - frame.left, top: asset.top - frame.top, width: asset.width, height: asset.height } }
function constrainPan(next: { x: number; y: number }) { if (!media.value || !stage.value) return next; const scale = zoom.value / 100; const maxX = Math.max(0, ((media.value.width ?? 0) * scale - stage.value.clientWidth) / 2); const maxY = Math.max(0, ((media.value.height ?? 0) * scale - stage.value.clientHeight) / 2); return { x: Math.max(-maxX, Math.min(maxX, next.x)), y: Math.max(-maxY, Math.min(maxY, next.y)) } }
async function afterMediaLayout() { await nextTick(); requestAnimationFrame(() => { if (!hasFitted.value) fitToStage(); else { pan.value = constrainPan(pan.value); updateBounds() } }) }
function fitToStage() { if (!media.value || !stage.value) return; const scale = Math.min(1, stage.value.clientWidth / (media.value.width ?? 1), stage.value.clientHeight / (media.value.height ?? 1)); zoom.value = Math.max(25, Math.round(scale * 100)); pan.value = { x: 0, y: 0 }; hasFitted.value = true; void afterMediaLayout() }
function addRegion() { tool.value = 'region'; notify('请在图片上按住并拖拽，框选需要处理的区域。') }
function removeRegion(id: string) { snapshot(); regions.value = regions.value.filter(region => region.id !== id); if (selected.value === id) selected.value = null }
function undo() { const last = history.value.pop(); if (!last) return; redoStack.value.push(cloneRegions(regions.value)); regions.value = last; selected.value = regions.value.at(-1)?.id ?? null }
function redo() { const next = redoStack.value.pop(); if (!next) return; history.value.push(cloneRegions(regions.value)); regions.value = next; selected.value = regions.value.at(-1)?.id ?? null }
function setTool(next: Tool) { tool.value = next; notify(next === 'region' ? '框选工具已开启：在画面内按住并拖拽。' : '指针工具已开启：按住图片即可拖动画布；也可拖动选区或调整大小。') }
async function changeZoom(delta: number) { zoom.value = Math.min(200, Math.max(25, zoom.value + delta)); pan.value = constrainPan(pan.value); await afterMediaLayout() }
function point(event: PointerEvent) { const box = selectionLayer.value?.getBoundingClientRect(); if (!box?.width || !box.height) return { x: 0, y: 0 }; return { x: Math.max(0, Math.min(100, (event.clientX - box.left) / box.width * 100)), y: Math.max(0, Math.min(100, (event.clientY - box.top) / box.height * 100)) } }
function capture(pointerId: number) { selectionLayer.value?.setPointerCapture(pointerId) }
function startSelection(event: PointerEvent) { if (!media.value) return; if (tool.value === 'select') { panning.value = { start: { x: event.clientX, y: event.clientY }, origin: { ...pan.value } }; capture(event.pointerId); return } const start = point(event); snapshot(); drawing.value = start; const region = { id: crypto.randomUUID(), x: start.x, y: start.y, width: 0, height: 0 }; regions.value.push(region); selected.value = region.id; capture(event.pointerId) }
function beginTransform(event: PointerEvent, region: Region, kind: 'move' | 'resize') { if (tool.value !== 'select') return; event.preventDefault(); event.stopPropagation(); snapshot(); selected.value = region.id; transform.value = { id: region.id, kind, start: point(event), region: { ...region } }; capture(event.pointerId) }
function updateSelection(event: PointerEvent) { if (panning.value) { const active = panning.value; pan.value = constrainPan({ x: active.origin.x + event.clientX - active.start.x, y: active.origin.y + event.clientY - active.start.y }); void afterMediaLayout(); return } const current = point(event); if (transform.value) { const active = transform.value; const region = regions.value.find(item => item.id === active.id); if (!region) return; const dx = current.x - active.start.x, dy = current.y - active.start.y; if (active.kind === 'move') { region.x = Math.max(0, Math.min(100 - active.region.width, active.region.x + dx)); region.y = Math.max(0, Math.min(100 - active.region.height, active.region.y + dy)) } else { region.width = Math.max(1, Math.min(100 - active.region.x, active.region.width + dx)); region.height = Math.max(1, Math.min(100 - active.region.y, active.region.height + dy)) }; return } if (!drawing.value || !selected.value) return; const region = regions.value.find(item => item.id === selected.value); if (!region) return; region.x = Math.min(drawing.value.x, current.x); region.y = Math.min(drawing.value.y, current.y); region.width = Math.abs(current.x - drawing.value.x); region.height = Math.abs(current.y - drawing.value.y) }
function endSelection() { if (drawing.value && selected.value) { const region = regions.value.find(item => item.id === selected.value); if (region && (region.width < 1 || region.height < 1)) regions.value = regions.value.filter(item => item.id !== region.id) }; drawing.value = null; transform.value = null; panning.value = null }
function normalizeRange() { const max = duration.value; videoRange.value.start = Math.max(0, Math.min(max, Number(videoRange.value.start) || 0)); videoRange.value.end = Math.max(videoRange.value.start + .1, Math.min(max, Number(videoRange.value.end) || max)); if (videoRange.value.kind === 'custom' && videoRange.value.end <= videoRange.value.start) videoRange.value.end = Math.min(max, videoRange.value.start + .1) }
const observer = typeof ResizeObserver === 'undefined' ? null : new ResizeObserver(updateBounds)
function pickMedia() { input.value?.click() }
function onInputChange(event: Event) { const element = event.target as HTMLInputElement; void accept(element.files); element.value = '' }
function resetEditor() { media.value = null; regions.value = []; selected.value = null; history.value = []; redoStack.value = []; authorized.value = false; mode.value = 'crop'; quality.value = 90; outputFormat.value = 'png'; videoRange.value = { kind: 'all', start: 0, end: 0 }; tool.value = 'select'; zoom.value = 100; pan.value = { x: 0, y: 0 }; hasFitted.value = false; drawing.value = null; transform.value = null; panning.value = null; if (input.value) input.value.value = '' }
async function accept(files: FileList | File[] | null) { const file = files?.[0]; if (!file) return; try { media.value = await api.upload(file); regions.value = []; selected.value = null; history.value = []; redoStack.value = []; authorized.value = false; pan.value = { x: 0, y: 0 }; hasFitted.value = false; outputFormat.value = media.value.mediaType === 'video' ? 'mp4' : 'png'; videoRange.value = { kind: 'all', start: 0, end: media.value.duration ?? 0 }; await nextTick(); if (stage.value) observer?.observe(stage.value); await afterMediaLayout(); notify('文件已解析，可以标记需要处理的区域') } catch (error) { notify(error instanceof Error ? error.message : '文件上传失败') } }
async function create() { if (!media.value) return notify('请先选择一个文件'); if (!regions.value.length) return notify('请先在预览上拖拽框选需要处理的区域'); if (!authorized.value) return notify('请确认你拥有该文件的编辑权或已获得授权'); normalizeRange(); try { await api.create({ ...media.value, authorized: true, mode: mode.value, outputFormat: outputFormat.value, quality: quality.value, regions: regions.value, videoRange: videoRange.value }); await refresh(); resetEditor(); notify('任务已加入处理队列') } catch (error) { notify(error instanceof Error ? error.message : '创建任务失败') } }
onMounted(() => window.addEventListener('resize', updateBounds)); onBeforeUnmount(() => { observer?.disconnect(); window.removeEventListener('resize', updateBounds) })
</script>

<template>
  <section class="editor-page page"><header class="page-head"><div><h1>新建处理</h1><p>安全处理你有权编辑的图片与视频素材</p></div><button v-if="media" type="button" class="secondary" @click="pickMedia"><FolderOpen :size="17"/>更换文件</button></header>
    <input ref="input" class="media-input" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/quicktime,video/webm" @change="onInputChange"/>
    <div v-if="!media" class="dropzone" :class="{ dragging }" @dragover.prevent="dragging = true" @dragleave="dragging = false" @drop.prevent="dragging = false; accept($event.dataTransfer?.files || null)" @click="pickMedia"><Upload :size="32"/><h2>拖拽或选择图片、视频文件</h2><p>支持 JPG、JPEG、PNG、WEBP、MP4、MOV、WEBM，最大 {{ state.settings?.maxFileSizeMb ?? 500 }} MB</p><button type="button" class="primary">选择文件</button></div>
    <div v-else class="workspace"><main class="canvas-panel panel"><div class="toolbar"><button :class="{ active: tool === 'select' }" title="拖动画布" @click="setTool('select')"><MousePointer2 :size="18"/></button><button :class="{ active: tool === 'region' }" title="框选工具" @click="setTool('region')"><SquareDashedMousePointer :size="18"/></button><span/><button title="撤销" :disabled="!history.length" @click="undo"><RotateCcw :size="18"/></button><button title="重做" :disabled="!redoStack.length" @click="redo"><Redo2 :size="18"/></button><span/><button title="缩小" :disabled="zoom <= 25" @click="changeZoom(-10)"><ZoomOut :size="18"/></button><b>{{ zoom }}%</b><button title="放大" :disabled="zoom >= 200" @click="changeZoom(10)"><ZoomIn :size="18"/></button></div>
      <div ref="stage" class="media-stage" :class="{ drawing: tool === 'region' }"><img v-if="media.mediaType === 'image'" ref="mediaElement" :src="preview" :alt="media.filename" :style="assetStyle" @load="afterMediaLayout"/><video v-else ref="mediaElement" :src="preview" controls preload="metadata" :style="assetStyle" @loadedmetadata="afterMediaLayout"/><div ref="selectionLayer" class="selection-layer" :class="{ panning: !!panning }" :style="layerStyle" @pointerdown="startSelection" @pointermove="updateSelection" @pointerup="endSelection" @pointercancel="endSelection"><button v-for="region in regions" :key="region.id" class="region" :class="{ selected: selected === region.id }" :style="{ left: region.x + '%', top: region.y + '%', width: region.width + '%', height: region.height + '%' }" @pointerdown="beginTransform($event, region, 'move')" @click.stop="selected = region.id"><span>{{ regions.indexOf(region) + 1 }}</span><i v-if="selected === region.id" class="resize-handle" title="调整选区大小" @pointerdown="beginTransform($event, region, 'resize')"/></button></div></div>
      <footer><span>分辨率：{{ media.width }} × {{ media.height }}</span><span>格式：{{ media.mimeType.split('/')[1].toUpperCase() }}</span><span v-if="media.duration">时长：{{ media.duration.toFixed(1) }} 秒</span><span>大小：{{ (media.size / 1024 / 1024).toFixed(2) }} MB</span></footer></main>
      <aside class="inspector panel"><section><div class="inspect-head"><h2>处理区域</h2><button @click="addRegion">＋ 添加区域</button></div><div v-if="!regions.length" class="empty-regions">点击“添加区域”或工具栏的虚线框图标，再在预览上按住并拖拽以框选水印。</div><button v-for="(region, index) in regions" :key="region.id" class="region-row" :class="{ selected: selected === region.id }" @click="selected = region.id"><b>{{ index + 1 }}</b><span>选区 {{ index + 1 }}<small>矩形区域 · {{ Math.round(region.width) }} × {{ Math.round(region.height) }}%</small></span><Trash2 :size="17" @click.stop="removeRegion(region.id)"/></button></section>
        <section><h2>处理模式</h2><div class="mode-grid"><button v-for="[id, label, description] in modes" :key="id" :class="{ selected: mode === id }" :title="description" @click="mode = id">{{ label }}</button></div></section>
        <section><h2>输出设置</h2><label>输出格式<select v-if="!isVideo" v-model="outputFormat"><option value="png">PNG</option><option value="jpg">JPG</option></select><input v-else value="MP4" disabled/></label><label>输出质量<select v-model.number="quality"><option :value="80">标准（80%）</option><option :value="90">高（90%）</option><option :value="100">最高（100%）</option></select></label><template v-if="isVideo"><label>视频处理范围<select v-model="videoRange.kind"><option value="all">全片处理</option><option value="custom">指定时间段</option></select></label><div v-if="videoRange.kind === 'custom'" class="range-inputs"><label>开始（秒）<input v-model.number="videoRange.start" type="number" min="0" :max="duration" step="0.1" @change="normalizeRange"/></label><label>结束（秒）<input v-model.number="videoRange.end" type="number" min="0.1" :max="duration" step="0.1" @change="normalizeRange"/></label></div></template></section>
        <label class="consent"><input v-model="authorized" type="checkbox"/>我确认拥有文件编辑权，且不用于移除他人的版权、署名或权利管理信息。</label><button class="primary wide" @click="create"><Download :size="18"/>加入处理队列</button></aside></div>
  </section>
</template>
