import Database from 'better-sqlite3'
import fs from 'node:fs'
import path from 'node:path'
import type { Settings, Task, TaskStatus } from './types.js'

const root = process.cwd()
fs.mkdirSync(path.join(root, 'data'), { recursive: true })
export const db = new Database(path.join(root, 'data', 'frameclear.sqlite'))
db.pragma('journal_mode = WAL')
db.exec(`CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY, filename TEXT NOT NULL, mime_type TEXT NOT NULL, media_type TEXT NOT NULL, size INTEGER NOT NULL, width INTEGER, height INTEGER, duration REAL, input_path TEXT NOT NULL, output_path TEXT, output_size INTEGER, output_directory TEXT NOT NULL DEFAULT './outputs', output_format TEXT NOT NULL, quality INTEGER NOT NULL, mode TEXT NOT NULL, regions TEXT NOT NULL, video_range TEXT NOT NULL DEFAULT '{"kind":"all","start":0,"end":0}', retry_count INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL, progress INTEGER NOT NULL, step TEXT NOT NULL, error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);`)
for (const statement of ["ALTER TABLE tasks ADD COLUMN output_size INTEGER", "ALTER TABLE tasks ADD COLUMN output_directory TEXT NOT NULL DEFAULT './outputs'", "ALTER TABLE tasks ADD COLUMN video_range TEXT NOT NULL DEFAULT '{\"kind\":\"all\",\"start\":0,\"end\":0}'", "ALTER TABLE tasks ADD COLUMN retry_count INTEGER NOT NULL DEFAULT 0"]) { try { db.exec(statement) } catch { /* Existing installations already have the column. */ } }

const defaults: Settings = { concurrency: Number(process.env.DEFAULT_CONCURRENCY ?? 3), maxFileSizeMb: Number(process.env.MAX_FILE_SIZE_MB ?? 500), outputDirectory: process.env.OUTPUT_DIRECTORY ?? './outputs', defaultMode: 'crop', defaultFormat: 'png', defaultQuality: 90, autoRetryCount: 1, requestTimeoutMinutes: 30, maxResourcePercent: 70, theme: 'system' }
for (const [key, value] of Object.entries(defaults)) db.prepare('INSERT OR IGNORE INTO settings (key,value) VALUES (?,?)').run(key, JSON.stringify(value))
const rowToTask = (row: Record<string, unknown>): Task => ({ id: String(row.id), filename: String(row.filename), mimeType: String(row.mime_type), mediaType: row.media_type as Task['mediaType'], size: Number(row.size), width: row.width === null ? null : Number(row.width), height: row.height === null ? null : Number(row.height), duration: row.duration === null ? null : Number(row.duration), inputPath: String(row.input_path), outputPath: row.output_path ? String(row.output_path) : null, outputSize: row.output_size === null || row.output_size === undefined ? null : Number(row.output_size), outputDirectory: String(row.output_directory ?? defaults.outputDirectory), outputFormat: String(row.output_format), quality: Number(row.quality), mode: row.mode as Task['mode'], regions: JSON.parse(String(row.regions)), videoRange: JSON.parse(String(row.video_range ?? '{"kind":"all","start":0,"end":0}')), retryCount: Number(row.retry_count ?? 0), status: row.status as TaskStatus, progress: Number(row.progress), step: String(row.step), error: row.error ? String(row.error) : null, createdAt: String(row.created_at), updatedAt: String(row.updated_at) })
export const tasks = {
  list: () => (db.prepare('SELECT * FROM tasks ORDER BY created_at DESC').all() as Record<string, unknown>[]).map(rowToTask),
  get: (id: string) => { const row = db.prepare('SELECT * FROM tasks WHERE id=?').get(id) as Record<string, unknown> | undefined; return row ? rowToTask(row) : undefined },
  save: (task: Task) => db.prepare(`INSERT INTO tasks (id,filename,mime_type,media_type,size,width,height,duration,input_path,output_path,output_size,output_directory,output_format,quality,mode,regions,video_range,retry_count,status,progress,step,error,created_at,updated_at) VALUES (@id,@filename,@mimeType,@mediaType,@size,@width,@height,@duration,@inputPath,@outputPath,@outputSize,@outputDirectory,@outputFormat,@quality,@mode,@regions,@videoRange,@retryCount,@status,@progress,@step,@error,@createdAt,@updatedAt) ON CONFLICT(id) DO UPDATE SET output_path=excluded.output_path, output_size=excluded.output_size, output_directory=excluded.output_directory, output_format=excluded.output_format, quality=excluded.quality, mode=excluded.mode, regions=excluded.regions, video_range=excluded.video_range, retry_count=excluded.retry_count, status=excluded.status, progress=excluded.progress, step=excluded.step, error=excluded.error, updated_at=excluded.updated_at`).run({ ...task, regions: JSON.stringify(task.regions), videoRange: JSON.stringify(task.videoRange) }),
  remove: (id: string) => db.prepare('DELETE FROM tasks WHERE id=?').run(id)
}
export const getSettings = (): Settings => Object.fromEntries((db.prepare('SELECT * FROM settings').all() as {key:string;value:string}[]).map(r => [r.key, JSON.parse(r.value)])) as Settings
export const saveSettings = (partial: Partial<Settings>) => { for (const [key, value] of Object.entries(partial)) db.prepare('INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(key, JSON.stringify(value)); return getSettings() }
