<script setup lang="ts">
import { ref } from 'vue'
import { Download, Eye, FolderOpen, Image, Pause, Play, RotateCcw, Trash2, Video, X } from 'lucide-vue-next'
import { api } from '../lib/api'; import { notify, refresh } from '../stores/app'; import type { Task } from '../types'
defineProps<{tasks:Task[]; compact?:boolean}>()
const previewTask=ref<Task|null>(null)
const fmt=(n:number)=>n<1024*1024?`${Math.ceil(n/1024)} KB`:`${(n/1024/1024).toFixed(1)} MB`
async function action(id:string,a:string){try{await api.action(id,a);await refresh();notify(a==='reveal'?'已在 Finder 中显示处理结果':'任务操作已提交')}catch(e){notify(e instanceof Error?e.message:'操作失败')}}
async function remove(id:string){await api.remove(id);await refresh();notify('已删除历史记录，未删除输出文件')}
async function removeOutput(id:string){try{await api.removeOutput(id);await refresh();notify('已删除实际输出文件，历史记录仍保留')}catch(error){notify(error instanceof Error?error.message:'删除输出文件失败')}}
</script>
<template><div class="table-wrap"><table><thead><tr><th>任务名称</th><th>类型</th><th>处理进度</th><th>当前步骤</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="task in tasks" :key="task.id"><td class="file-cell"><component :is="task.mediaType==='image'?Image:Video" :size="20"/><span><b>{{task.filename}}</b><small>{{task.width }} × {{ task.height }} · 原始 {{fmt(task.size)}}</small><small v-if="task.outputPath" class="output-path" :title="task.outputPath">结果：{{task.outputPath}} · {{fmt(task.outputSize ?? 0)}}</small></span></td><td>{{task.mediaType==='image'?'图片':'视频'}}<small>{{task.outputFormat.toUpperCase()}}</small></td><td><div class="progress-value"><span>{{task.progress}}%</span><i><em :style="{width:task.progress+'%'}"></em></i></div></td><td>{{task.error || task.step}}<small v-if="task.retryCount">已自动重试 {{task.retryCount}} 次</small></td><td><span class="status" :class="task.status.toLowerCase()">{{task.status}}</span></td><td class="actions"><button v-if="task.status==='Completed' && task.outputPath" title="预览结果" @click="previewTask=task"><Eye :size="16"/></button><a v-if="task.status==='Completed' && task.outputPath" :href="`/api/tasks/${task.id}/download`" title="下载结果"><Download :size="16"/></a><button v-if="task.status==='Completed' && task.outputPath" title="在文件夹中显示" @click="action(task.id,'reveal')"><FolderOpen :size="16"/></button><button v-if="task.outputPath" title="删除输出文件" @click="removeOutput(task.id)"><Trash2 :size="16"/></button><button v-if="task.status==='Processing'" title="暂停" @click="action(task.id,'pause')"><Pause :size="16"/></button><button v-if="task.status==='Paused'" title="继续" @click="action(task.id,'resume')"><Play :size="16"/></button><button v-if="['Failed','Cancelled'].includes(task.status)" title="重试" @click="action(task.id,'retry')"><RotateCcw :size="16"/></button><button v-if="['Waiting','Processing','Paused'].includes(task.status)" title="取消" @click="action(task.id,'cancel')"><X :size="16"/></button><button title="删除历史记录" @click="remove(task.id)"><Trash2 :size="16"/></button></td></tr><tr v-if="!tasks.length"><td colspan="6" class="empty">暂时没有任务。</td></tr></tbody></table></div><Teleport to="body"><div v-if="previewTask" class="preview-backdrop" @click.self="previewTask=null"><section class="preview-dialog panel" role="dialog" aria-modal="true" aria-label="处理结果预览"><header><div><h2>处理结果预览</h2><p>{{previewTask.filename}}</p></div><button title="关闭预览" @click="previewTask=null"><X :size="20"/></button></header><div class="preview-media"><img v-if="previewTask.mediaType==='image'" :src="`/api/tasks/${previewTask.id}/preview`" :alt="`${previewTask.filename} 的处理结果`"/><video v-else :src="`/api/tasks/${previewTask.id}/preview`" controls preload="metadata"/></div><footer><span class="status completed">处理成功</span><a class="primary" :href="`/api/tasks/${previewTask.id}/download`"><Download :size="16"/>下载结果</a></footer></section></div></Teleport></template>
